# Generated by Django 5.1.4 on 2025-01-12 09:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='users',
            name='displayname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Username can only contain letters, numbers, dots, and underscores.', regex='^[A-Za-z0-9._]+$')]),
        ),
    ]
